### ISSUE TITLE
Look into benefits of Open Source Initiative Incubator program

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/funding#2]
While at FOSDEM this past weekend, I saw a lightening talk by cool project called [Snowdrift.coop](https://snowdrift.coop) who are building something exciting- a means to getting sustainable / ethical funding for FOSS projects. Once they launch their platform, we should definitely consider being a project on there to 

However, they also mentioned being a part of the [Open Source Intiative's Incubator](https://opensource.org/working_groups) which makes it easy for open source projects to accept donations among other things. It's worth looking into this for our community and projects!

**Comment by davelab6** [comment]
I've followed Snowdrift for a few years, and I think their model could be adopted by any project using a simple spreadsheet and gumroad or so; the fact that NO project has tried a 'mvp' approach is worrying.

**Comment by jdittrich** [comment]
@davelab6 : With "them" you mean the Open Source Initiative Incubator?

**Comment by bnvk** [comment]
@davelab6 do you mean mean "them" as Snowdrift or Open Source Initiative?

**Comment by davelab6** [comment]
I meant Snowdrift. Updated my comment to clarify. 

I also think www.sfconservancy.org is a better fiscal home for libre projects than OSi, since it actively defends copyleft.

**Comment by bnvk** [comment]
@davelab6 cool to know about SF Conservancy as well. Thanks :+1:

**Comment by wolftune** [comment]
OSI does not and will not support software projects directly. Their entire focus and incubator program is specifically for things that are meta general stuff about the nature of Open Source overall. They are not supporting Snowdrift.coop for being a software project but as a meta issue that involves research and concepts around Open Source concerns more broadly.

SF Conservancy is a fiscal sponsor for free/libre/open software projects. Inkscape is one of their projects, for example.

In our case with Snowdrift.coop, SF Conservancy's scope doesn't fit. We're not a simple software project, we're a broader scope cooperative organization aiming to cover FLO projects of all sorts, including art, research, education, etc. and not just software. It's really beyond SFC to consider working with us, but they are interested in signing up their projects to work with us once we're launched.

So, if you're talking about support for particular software projects, I agree that SFC is better. If you're talking about something different and more meta, maybe OSI makes sense, but hard to say without more details.

The challenges in getting Snowdrift.coop launched are _mostly_ not about whether you can build a simple MVP of the pledge formula (that's no big deal). It's mostly about clarifying and presenting everything clearly since it's a new model that people aren't familiar with and the challenges of deciding all the specific details including running it as an organization itself. We're working out the cruft and getting focused and struggling through learning to best manage our scope currently, and we hope to get going finally soon.

**Comment by davelab6** [comment]
@wolftune I don't want to be dismissing and wish you all the best of luck with it! :)

**Comment by wolftune** [comment]
@davelab6 thanks, and I know you wish the best for everyone. I do want the focus here to be clear and not lost: SF Conservancy is good for specific software projects, OSI is good for meta FLO-related research / general FLO issue type projects

**Comment by davelab6** [comment]
@wolftune right; this issue is, I think, about where are good place for projects to tuck away cash, and I think SFC is the best generic spot. (I personally work with TUG.org to store libre font cash.) And its interesting to note that OSi isn't actually offering such a spot for general projects, and Snowdrift has special status because of its 'meta' nature. :)

**Comment by bnvk** [comment]
I've ported this information out to [organization repo](https://github.com/opensourcedesign/organization/) now!
