### ISSUE TITLE
Explore "recurring" funding platforms / approaches for projects

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/funding#4]
_Ported this issue with thoughts from #2 to keep things focused, as @davelab6 brought up_

> I've followed Snowdrift for a few years, and I think their model could be adopted by any project using a simple spreadsheet and gumroad or so; the fact that NO project has tried a 'mvp' approach is worrying.

I _think_ having a dedicated platform / tool / community is often helpful in growing involvement much more so than just isolated "donate" buttons + spreadsheets (hidden from public), something our species brains, mirror neurons, and social feedback loops... I dunno!

Unless I'm misunderstanding "NO project has tried a mvp..." I think a lot of FOSS makers / tinkerers don't have a "product" focus, nor business acumen / interest in raising money and keeping that whole side of things going- but I don't think that means they wouldn't quite their day jobs to work on their passion project, if they could make a decent living! 

Exploring these sort of unusual funding / product development models is something i've been interested in since joining this community and open source in general!

**Comment by evalica** [comment]
1. https://freedomsponsors.org/
2. https://www.bountysource.com/

**Comment by evalica** [comment]
Less "orthodox" + based on timed campaigns:
3. https://www.patreon.com/
4. https://www.indiegogo.com/
5. https://www.kickstarter.com/

**Comment by wolftune** [comment]
Don't recreate all the research. Here's the entire everything: https://snowdrift.coop/p/snowdrift/w/en/othercrowdfunding

**Comment by davelab6** [comment]
> I think having a dedicated platform / tool / community is often helpful in growing involvement much more so than just isolated "donate" buttons + spreadsheets (hidden from public), something our species brains, mirror neurons, and social feedback loops... I dunno!

I think the main reason platforms outperform homepages is that they have capital investment to pump prime the process: having paid staff who are competent at writing sales newsletters and homepage content to start driving attention and traffic to their platform matters. 

I've run a bunch of libre font kickstarters - http://fundwebfonts.appspot.com - and, well, you can see the one that the Kickstarter staff made into a 'project we love' and promoted through their channels ;)

> Unless I'm misunderstanding "NO project has tried a mvp..."

I think so - I should have said, "afaik NO project has tried a minimum viable snowdrifting funding process" :) 

The snowdrift folks have spend literally YEARS building a platform for a funding model which no one I know of has proven actually works at a small scale. It wasn't used to fund the initial project development, even :(  So I'm a bit skeptical if the model is even all that compelling, and I wonder that they are wasting their time on building something big without having done enough 'controlled experiments' first. 

> I think a lot of FOSS makers / tinkerers don't have a "product" focus, nor business acumen / interest in raising money and keeping that whole side of things going- but I don't think that means they wouldn't quit their day jobs to work on their passion project, if they could make a decent living!

I feel disappointed when people get all 'oh, I can learn computer science [or UX design or whatever], but I just can't bring myself to learn the most basic things about doing business online, in the 21st century, when it is easier than ever in history.' 

I think things like PayPal and nowadays http://www.gumroad.com takes so much pain away from selling things online, and so many people are habituated to pay for binaries, that a lot of free software projects are leaving a lot of money on the table by not selling them - especially for non-libre desktop OSs. Here are some examples:
- http://ardour.org/download.html offers GPL binaries for a fee
- http://synergy-project.org/pricing offers GPL binaries for a fee
- http://primarypad.com funds Etherpad developement by offering a paid subscription to schools
- https://guardianproject.info/home/partners/ android privacy tools. Sponsored by human rights foundations
- https://payments.discourse.org/buy/ offers GPL source as a hosted web app service
- https://prototypo.io offers GPL source as a hosted web app service
- http://jsbin.com/  offers MIT source as a hosted web app service

I think Patreon and Snowdrift and Gratipay are much more interesting than Kickstarter or IndieGoGo because developing software is a neverending process; this is why Adobe and MS and all the other proprietary software developers from the 80s/90s/00s have switched to subscription based revenue models, "Creative Cloud" etc.

I was amazed to see this blogger I follow getting a substantial income on Patreon, https://www.patreon.com/waitbutwhy - and the fees are low enough that I think it is a good way to hand off the subscription/payments/customer-service/etc side of things at the beginning to focus on execution - https://patreon.zendesk.com/hc/en-us/articles/204606125-How-do-you-calculate-fees-

I think the most important thing for that execution and for its sales and marketing is having **VERY** solid [program management](https://en.wikipedia.org/wiki/Program_management) in place, so that prospects and customers can see what the roadmap is and, most importantly, see that progress is being made against that roadmap on time and on point. 

Few projects have basics like GANTT charts of development, or user stories on a kanban board, or whatever; usually its 100s of unsorted Issues in a bug tracker and a "TODO" list of ideas.. I think with more roadmap structure, projects can put a price tag on each row or story and allow their customers to vote by apportioning their subscription fees to the things they want to see worked on. 

http://flattr.com works like that for the whole web, but I think it is a bit of a nebulous concept. In "commodity markets" then branding and positioning is **critical** to success, and nebulous positioning is poisonous. Mako has this great lecture about why it was that Wikipedia took off and not there many many other similar projects at that time that did not: https://www.youtube.com/watch?v=UlvxtqxFwiQ

With the advice in the lecture in mind, I think it is better that makers learn a little bit of product management, copywriting, and business basics - no need to raising money, maybe need to spend $100 on freelancer.com to get a graphic designer to improve the homepage into an landing page that converts efficiency - and earn enough money to involve a sales and marketing contractor (paid on percentage) to grow the funnel. 

Really the biggest critique I have for https://snowdrift.coop is that it seems to me like a feature idea, not a product; it is an interesting way to accelerate customer growth on a subscription basis, but there is so much more to running a (co-operative, ethical) libre software development business that they aren't handling. 

I also found http://www.fund-io.com as another interesting way to accelerate customer growth. This 'contracted to become libre' model can work on a subscription basis, and I do wonder that this model could be more effective, although it is not so ethically pure, heh.

Also also, I recently read and recommend these great articles on funding subaltern cultural projects:
- https://modelviewculture.com/pieces/funding-model-view-culture
- https://modelviewculture.com/pieces/using-crowdfunding-to-support-your-work
- https://modelviewculture.com/pieces/tag/funding

**Comment by wolftune** [comment]
Everything @davelab6 is saying is sensible, except he's just giving impressions about the issues with Snowdrift.coop. The _primary_ distractions about what we've been doing are about learning all this stuff and about running with 100% FLO tools.

I didn't start out a business expert _or_ a coder and never felt I could do any of this without help from those with other skills, so it becomes about recruiting others. The first several years of work on Snowdrift.coop were literally just figuring out what this was, how to run a FLO project at all, and the only real developer did not have business and project management experience and was only putting in spare time on some weekends. We've had a more dedicated developer for a little less than a year now, and that's when we sort of dealt with things from there.

For example, we didn't even have a mailing list set up until maybe 9-10 months ago. Which was super frustrating, but I know nothing about this sysadmin stuff and was asking for others to figure this out and disappointed about the delays in getting that. We just settled on using OpenProject for better project management about a week ago now. And we spent annoying time 8 months ago figuring out what to do when Gitorious shut down. Basically, compromising and just using GitHub (despite being proprietary) would have made things easier. We want to do MVP, but we want/wanted to try to do it without compromising FLO values.

Anyway, we're finally on track to get things worked out, but still some stuff to do. We have a user researcher on board now… Anyway, I don't want to go on and on about the details. The reason we're in better shape to getting going now is because more people now (like William "Salt" Hale who presented at FOSDEM) have decided to actually participate and offer their skills to make it happen rather than only offer (still quite welcome) critiques from the sidelines. The challenges of running a project and even learning about business organizing are vast if you don't already have these skills. Snowdrift.coop wasn't started by people who wanted to learn these skills or do our own thing to do it, it was started with the aim of finding people who wanted to help us make a viable MVP and do the research and everything… anyway, our proposed model a year ago was similar but too complex and we've done research which has helped us redesign to a more workable approach, and now we're ready to sort priorities and get the prototype working soon.

**Comment by wolftune** [comment]
Anyway, so it's not lost in tangential discussion (stupid lack of threading on GitHub!), anyone looking into services/options/platforms, here's the complete run-down: https://snowdrift.coop/p/snowdrift/w/en/othercrowdfunding

**Comment by davelab6** [comment]
@wolftune thanks for the update! https://snowdrift.coop/p/snowdrift/w/en/othercrowdfunding is now really awesome and much longer than last time I looked :D

**Comment by evalica** [comment]
@wolftune thanks for linking to the research. Awesome work!

**Comment by bnvk** [comment]
@wolftune @evalica @davelab6 really great info and discussion! Thanks so much you all :)

**Comment by simonv3** [comment]
Shoulda posted my post about fundclub here. Sorry!

> This is awesome. I want to point out fundclub: http://joinfundclub.com/
> 
> Basically it's an e-mail list that sends out an e-mail every month with "fund this diverse / social justice in tech" organization with 100 of your moneys. It's a different organization every month. If you don't donate you get booted off the list (the idea being that it becomes sustainable). Every month so far it's been able to generate about $6000-9000 for the relevant project and it's only been going for 6 months or so. This means that only 60-90 people have been contributing, but it's made a huge impact on the projects involved.
> 
> It'd be cool to fund open source design projects in the same way. Share some wealth.

**Comment by wolftune** [comment]
FWIW, Fund Club is already listed at https://snowdrift.coop/p/snowdrift/w/en/othercrowdfunding — it is _that_ thorough… ;)

**Comment by simonv3** [comment]
Heh, @wolftune thanks for the link. I got excited about all the talk, did a quick search and didn't see a mention of fundclub, and decided to throw it in the ring, only making my way through all of the actual reading now.

**Comment by davelab6** [comment]
Also, hadn't seen http://www.gnu.org/philosophy/funding-art-vs-funding-software.html before although its been out a while, interesting background reading.

**Comment by gusaus** [comment]
Hi there - 

Not only is it a promising new crowdfunding platform, [OpenCollective](https://opencollective.com/) has a pretty diverse cross section of OSS communities, projects, orgs, and individuals in their [Slack channel](https://slack.opencollective.com/) - They're also [open source](https://github.com/OpenCollective), so there could be ways to collaborate with them directly in addition to the many communities, including ours, who may need design talent.

**Comment by simonv3** [comment]
Yeah I can definitely +1 Open Collective. I'm fairly sure I've brought it up before for OSD, but it might have been in IRC. If someone wants to go through the process of getting OSD on open collective, I think that would be fantastic. 

We use it for OpenFarm and we haven't pushed it too heavily yet to our user base, but I'm looking forward to doing so. 

You just have to e-mail Pia Mancini pia@opencollective.com, supply them with the logo, a hero image, what our mission is (copied from the website, possibly) and who the contributors are. 

@gusaus, do you want to take initiative on this? 

This would make it possible for us to handle the sticker thing in the promotional materials thread.
https://github.com/opensourcedesign/events/issues/43#issuecomment-253455023

**Comment by gusaus** [comment]
My recommendation would be to read up on [OpenCollective](https://opencollective.com/) and if it sounds like there's potential benefit, join their Slack channel (https://slack.opencollective.com/) and ask @piamancini to walk you through their process. Also feel free to join us in #openproducer!

**Comment by piamancini** [comment]
hi @simonv3 @gusaus thank you for the mention. 
Happy to help anyone come on board, it's pretty straight forward. You can apply directly from your github repo here: https://opencollective.com/opensource/apply This will bring on board the core contributors you select and automatically fetch everyone else as contributors. 
Let me know how it goes. 
best

**Comment by ei8fdb** [comment]
At risk of asking a silly question: how could Open Collective help us, and what would we contribute to Open Collective?

I’m not very good with things like funding and frameworks.

**Comment by simonv3** [comment]
@ei8fdb I think there's two levels of involvement being proposed for OSD within Open Collective. 

The first level of involvement is Open Source Design sets itself up with a Open Collective "organization" page. See this example for [OpenFarm](https://opencollective.com/openfarm). The idea here is that people contribute small amounts ($1 - large) on a monthly or one-off basis that Open Source Design can then use to, for example, pay a designer to do a design, or on a smaller scale, pay for Open Source Design logos and hosting costs (not that we have any at the moment). 

Then there's the second level of involvement which is that Open Source Design members join the Open Collective community. I don't really see a need for this personally and IMO would just spread things to thin, but people are free to go hang out where they want. 

I think the first level of involvement is probably a good thing, but can cause complications in how OSD is run and what it's for.

**Comment by ei8fdb** [comment]
Thanks for explaining is Simon.

> The first level of involvement is Open Source Design sets itself up with a Open Collective "organization" page. See this example for OpenFarm. The idea here is that people contribute small amounts ($1 - large) on a monthly or one-off basis that Open Source Design can then use to, for example, pay a designer to do a design, or on a smaller scale, pay for Open Source Design logos and hosting costs (not that we have any at the moment).

This seems to make sense to me. I’d like to be able to contribute a few pounds a month (e.g. for stickers!) to OSD.

If there’s no objections I can try to create an organisation page for us. I’ll share the details with whoever wants them.

> Then there's the second level of involvement which is that Open Source Design members join the Open Collective community. I don't really see a need for this personally and IMO would just spread things to thin, but people are free to go hang out where they want.

This also makes sense. Then I’d have more IRC/Mattermost instances to keep track of :)

> I think the first level of involvement is probably a good thing,

Agreed.

> but can cause complications in how OSD is run and what it's for.

I guess you mean about the second level of involvement?

**Comment by simonv3** [comment]
I just meant that once you start involving money things become complicated. Who controls what the money goes to, etc. 

If you could set up the organization page for us that'd be great. Unfortunately I don't think we qualify to go through the process through the automatic set up (none of our repositories have 100 stars even though some of them have 100+ watchers).

**Comment by piamancini** [comment]
Hi @simonv3 @ei8fdb use this link to create an organisation https://opencollective.com/create choose 'Other' (if you hit opensource, it'll redirect to github) I'll add it to open source manually. :)

PS: I agree with @simonv3 no need to hang out in the community to have a collective. Of course you are super welcome to contribute, but it's besides the point.

**Comment by simonv3** [comment]
I just spent a long time tracking this issue down, we really need to deal with our plethora of issues. 

Just going to tag this issue here as well: https://github.com/opensourcedesign/organization/issues/35

**Comment by simonv3** [comment]
We now have recurring funding here: 

https://opencollective.com/opensourcedesign

This is a big deal 🎺  🎺  🎺 . @jancborchardt should probably invite some other people to be contributors to the project, but aside from that, we're already getting some money. If a couple more people pitch in we might even be considered sustainable?

**Comment by jancborchardt** [comment]
How can I invite other people to be contributors cc @piamancini? :)

**Comment by equinusocio** [comment]
>We now have recurring funding here:
>https://opencollective.com/opensourcedesign

Awesome!

**Comment by piamancini** [comment]
@jancborchardt for the moment please send me their emails pia@opencollective.com :( 
We will be working on allowing users to add contributors themselves soon
Just fyi people I add as core contributors will be able to edit content and approve expenses.

**Comment by equinusocio** [comment]
@piamancini 
PS: My open collective personal profile page doesn't work.
https://opencollective.com/astorino.design

Maybe because i have a dot inside the username, but i can't edit it since i'm not able to access to my profile.

**Comment by piamancini** [comment]
looking into it @equinusocio thank you

**Comment by piamancini** [comment]
@equinusocio it's the '.' on the username. I removed it, it's live now. Sorry, we should do a better job at not letting you use it.

**Comment by jancborchardt** [comment]
@piamancini thanks, mailed you :)

**Comment by bnvk** [comment]
> We now have recurring funding here: 
> 
> https://opencollective.com/opensourcedesign

HOORAY!!! Much gratitude to the folks at Open Collective thank you @piamancini 
for helping make this happen!
 
> This is a big deal 🎺  🎺  🎺 . @jancborchardt should probably invite some 
> other people to be contributors to the project, but aside from that, we're 
> already getting some money. If a couple more people pitch in we might even 
> be considered sustainable?

This is wonderful to see this happen so quickly :D

I'm going to prune out these URLs and such into a page in the
[opensourcedesign/organization](https://github.com/opensourcedesign/organization)
repository just so we don't lose the value discussion here!

**Comment by piamancini** [comment]
hey everyone!  This is the link to the interview Aseem did with you https://medium.com/open-collective/meet-the-open-source-design-collective-96e81261f76#.pjr5fdwbk
<3 <3
